Repository UofTTeam2/TravIS, pull requests merged in 2023-10, with the labels that each got.

#17 Implement User Authentication and CRUD Operations
  .env.Example
  config/connection.js
  controllers/api/index.js
  controllers/api/user-routes.js
  controllers/home-routes.js
  controllers/homepage.js
  controllers/index.js
  db/schema.sql
  files/workFlow.md
  package-lock.json
  package.json
  public/css/style.css
  public/js/login.js
  public/js/logout.js
  public/js/updateDelUser.js
  server.js
  utils/auth.js
Labels: documentation, enhancement

#18 Implement Models and Seeds for User, Trip, TripSection, ItineraryItem, Message, and Comment
  controllers/api/user-routes.js
  controllers/home-controller.js
  controllers/index.js
  files/workFlow.md
  models/Comment.js
  models/ItineraryItem.js
  models/Message.js
  models/Session.js
  models/Trip.js
  models/TripSection.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  seeds/comment-seeds.js
  seeds/index.js
  seeds/itineraryitem-seeds.js
  seeds/message-seeds.js
  seeds/trip-seeds.js
  seeds/tripsection-seeds.js
  seeds/user-seeds.js
  server.js
  utils/dataParser.js
Labels: documentation, enhancement

#19 Implement CRUD APIs for Trip, Trip Section, and Itinerary Item Models
  controllers/api/index.js
  controllers/api/trips-controller.js
  controllers/api/user-controller.js
  controllers/home-controller.js
  controllers/index.js
  controllers/trip-controller.js
  models/ItineraryItem.js
  models/Trip.js
  models/TripSection.js
  public/js/login.js
  seeds/trip-seeds.js
  seeds/tripsection-seeds.js
Labels: documentation, enhancement

#20 Improvements and Fixes in Expenses, Public Attributes, revising Comment table, and Session Handling
  controllers/api/trips-controller.js
  controllers/trip-controller.js
  db/schema.sql
  models/Comment.js
  models/Session.js
  models/Trip.js
  package.json
  seeds/comment-seeds.js
  seeds/trip-seeds.js
  server.js
Labels: enhancement

#22 Bad Request
  controllers/api/trips-controller.js
  controllers/home-controller.js
  public/css/style.css
  views/bad-request.handlebars
Labels: enhancement

#23 Add Forum API and Seeder, Update Models and Middlewares
  controllers/api/forumApi-controller.js
  controllers/api/index.js
  controllers/api/trips-controller.js
  controllers/forum-controller.js
  controllers/index.js
  controllers/trip-controller.js
  models/Comment.js
  models/Message.js
  models/Post.js
  models/Topic.js
  models/index.js
  public/js/login.js
  seeds/comment-seeds.js
  seeds/index.js
  seeds/message-seeds.js
  seeds/post-seeds.js
  seeds/topic-seeds.js
  utils/userIdAuth.js
Labels: documentation, enhancement

#24 [Feature] Add README.md with Project Details
  .env.Example
  README.md
  package-lock.json
  package.json
Labels: documentation

#28 Create Search and Recommendations for Points of Interest.
  .env
  .env.Example
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  LICENSE
  package-lock.json
  public/css/style.css
  seeds/itineraryitem-seeds.js
  utils/auth.js
  utils/dataParser.js
  views/cityResults.handlebars
  views/search.handlebars
Labels: documentation, enhancement

#33 This feature adds Search and Results pages for city recommendations and info
  controllers/home-controller.js
  public/css/style.css
  views/cityResults.handlebars
  views/partials/dashSide.handlebars
  views/search.handlebars
Labels: documentation, enhancement

#34 Fix/integrating the mess
  README.md
  controllers/api/forumApi-controller.js
  controllers/home-controller.js
  public/css/style.css
  public/js/login.js
  public/js/logout.js
  public/js/updateDelUser.js
  views/cityResults.handlebars
  views/home.handlebars
  views/layouts/main.handlebars
  views/newpost.handlebars
  views/partials/dashSide.handlebars
  views/topic.handlebars
Labels: enhancement

#35 fix(navmenu hamburger): fixed several issues regarding the navbar ham…
  public/css/style.css
  public/js/index.js
  public/js/toggler-navmenu.js
  views/partials/header.handlebars
Labels: enhancement
